### ISSUE TITLE
Split rules into individual files

### ISSUE THREAD

**Issue by jhgg** [dittos/graphqllib#19]
Would it be beneficial to split rules into individual files? Looking at it, it looks like `rules.py` is going to get pretty big. Perhaps we should put them in `rules/__init__.py` and each rule in `rules/{rule_name}.py`?

**Comment by rawls238** [comment]
:+1: to this, the reference implementation follows the same pattern

**Comment by dittos** [comment]
With 9 rules out of 22, `rules.py` is now 280 lines. I think ~700 lines when complete is not that big. Also, it seems that single huge module file is common practice in Python libs (unlike JS).

**Comment by jhgg** [comment]
Some rule files seem to be pretty big. I think that it will end up being in the 2k loc range. Also splitting them up will avoid merge conflicts better. Seems like small trade off for large benefit. Your decision.

**Comment by jhgg** [comment]
So. I was pretty far off. With all rules implemented the file is 970 lines. 

I still think we should split it. It's unwieldily to work with.

**Comment by rawls238** [comment]
we should probably close this?

**Comment by jhgg** [comment]
Resolved in https://github.com/graphql-python/graphql-core/commit/a88c628b03d0b790dcc57230307c0dd8b78cc6fa
