### ISSUE TITLE
[perf] Refactor: namedtuples to structs 

### ISSUE THREAD

**Issue by jhgg** [dittos/graphqllib#30]
After #6 we should look at moving away from namedtuples to "structs" which is really just a class with __slots__ (can even use `exec` to codegen similar to namedtuple). You'll see a ~3x increase in access speed on py27. A bit of a PMO. But leaving this here because it'd be pretty much transparent to the API. `namedtuples` incur a performance penalty when accessing by attr vs by index. A class like:

```
class A(object):
   __slots__ = 'b', 'c'
   def __init__(self, b, c): 
        self.b, self.c = b, c

```

Actually ends up being much faster:

```
In [1]: from collections import namedtuple
In [2]: class A(object):
   ...:        __slots__ = 'b', 'c'
   ...:        def __init__(self, b, c):
   ...:                 self.b, self.c = b, c
   ...:

In [3]:
In [4]: A_t = namedtuple('A', 'b c')
In [5]: a_t = A_t(1, 2)
In [6]: a = A(1, 2)
In [7]: %timeit a.b
10000000 loops, best of 3: 44.5 ns per loop

In [8]: %timeit a_t.b
10000000 loops, best of 3: 131 ns per loop
```

**Comment by woodb** [comment]
Very cool! Are there any known limitations or platform differences when using `__slots__` over something like a `namedtuple`? While the 3x improvement shown is great, it's still sub microsecond for both, which is pretty damned fast. Is it slower to instantiate? Set attributes? I'm just curious in general.

Tangentially, I think this could open up a wider discussion on adding some kind of benchmarking suite, such as [asv](https://github.com/spacetelescope/asv) or [vbench](https://github.com/pydata/vbench), to the project to more widely quantify performance degradation or enhancements.

**Comment by jhgg** [comment]
It would be a non-issue if we chose to switch to the C++ parser implementation from Facebook. There are cython bindings for it, but they still need a little bit of work.

Either way. Switching from namedtuples to slotted classes is as simple as switching stuff in ast.py. Shouldn't require any other changes.  

The cost to construct should be about the same. Setting attributes isn't possible with namedtuples so hard to compare!

**Comment by jhgg** [comment]
Also I think that pypy can emit way more efficient code for slotted classes compared to named tuples.

**Comment by dittos** [comment]
I don't have much opinion on this. I was just lazy to implement all AST types as class.

**Comment by dittos** [comment]
I found that libgraphqlparser generates AST code from language-independent definition DSL. https://github.com/graphql/libgraphqlparser/blob/master/ast/ast.ast Maybe we can leverage this.

**Comment by jhgg** [comment]
I think we should look into leveraging work done by @mpaolini in https://github.com/elastic-coders/py-graphqlparser

**Comment by mpaolini** [comment]
@jhgg please do open an issue on `py-graphqlparser` repo showing the python API you need for `grapqhqllib` so I we can start working on it

**Comment by jhgg** [comment]
I will take a shot at on Monday, @mpaolini .

**Comment by mpaolini** [comment]
dict is even faster (expecially on python 3):

```python
setup = '''
from collections import namedtuple
class A(object):
    __slots__ = 'b', 'c'
    def __init__(self, b, c):
        self.b, self.c = b, c

A_t = namedtuple('A', 'b c')
a_t = A_t(1, 2)
a = A(1, 2)
a_d = {'b': 1, 'c': 2}
'''

import timeit
import sys
print('version info: {}'.format(sys.version_info))
for stmt in ['a.b', 'a_t.b', 'a_d["b"]']:
    print('{}: {}'.format(stmt, timeit.timeit(stmt, setup=setup)))
```

results:

```
version info: sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
a.b: 0.0417280197144
a_t.b: 0.112826108932
a_d["b"]: 0.0410261154175
```

```
version info: sys.version_info(major=3, minor=5, micro=0, releaselevel='final', serial=0)
a.b: 0.03365939999639522
a_t.b: 0.061670883995248005
a_d["b"]: 0.03001770300033968
```

**Comment by dittos** [comment]
#42 fixes this.
