### ISSUE TITLE
Django Support

### ISSUE THREAD

**Issue by jhgg** [dittos/graphqllib#44]
Issue to discuss Django support. I think as a few design goals, we need to consider:

- [ ] Generate GraphQL types based off of Model introspection (or explicit definition). 
   - [ ] Explicitly include/exclude fields (a-la DJRF)
   - [ ] Auto-generate CUD mutations.
- [ ] Detect graphql queries that would result in related or prefetch query and pass that information to Django. (`QuerySet.select_related(...)`, `QuerySet.prefetch_related(...)`)
- [ ] Detect what files are actually needed to fulfill a query, and avoid fetching those from the DB if not needed. `QuerySet.only(...)`

**Comment by jhgg** [comment]
Suppose I have two models:

```python
class Person(models.Model)
    name = models.CharField(...)
    profile_picture = models.ForeignKey('ProfilePicture')
    friends = models.ManyToManyField('self')
    location = models.ManyToManyField('Location')

class ProfilePicture(models.Model):
    image = models.FileField(...)
    created_on = models.DateTimeField(...)

class Location(models.Model):
    country = models.CharField(...)
    latitude = models.FloatField(...)
    longitude = models.FloatField(...)

```

I should be able to execute a query like:

```
{
    user(id: 5) {
        name,
        location {
            country
        },
        friends {
            name
        }
    }
```

And it should be able to generate a query like:

```
User.objects.only('name').select_related('location__country').prefetch_related(Prefetch('friends', queryset=Person.objects.only('name'))).get(id=5)
```

**Comment by ivome** [comment]
This is a great idea! Some more things we could consider when we start implementing something like that:
- Possibility to add aggregations to the database query. Think of the following query: 
```
{
    user(id: 5) {
        name,
        friendsCount,
        friends {
            name
        }
    }
}
```
- A permission layer. Different clients might have access to different objects and attributes in the graph. It would be great, if that implementation could already apply those filters before creating the query and only request the data from the database that it has access to. If someone does not have access to the location object, this query
```
{
    user(id: 5) {
        name,
        location {
            country
        },
        friends {
            name
        }
    }
}
```
could result in such a queryset:
```
User.objects.only('name').prefetch_related(Prefetch('friends', queryset=Person.objects.only('name'))).get(id=5)
```
and return this result:
```
{
    "5": {
        "name": "Jake H",
        "location": null,
        "friends": [
            {
                "name": "Taheo K"
            },
            {
                "name": "Brandon W"
            }
        ]
    }
}
```

**Comment by woodb** [comment]
I feel like integrations with other libraries should be separate projects, like a `django-graphql` that uses `graphqllib`.

I'm not sure what @dittos plan for this is, but I sort of imagined it as being a library for working with GraphQL and nothing more. Thoughts?

**Comment by woodb** [comment]
It looks like there was code for Django that was removed a few days ago in https://github.com/dittos/graphqllib/commit/7eb5a26661c4f4b042182287ccad5532528c14f6

**Comment by jhgg** [comment]
I'm cool with a separate library ontop of this. Or some contrib package for django.

**Comment by woodb** [comment]
@jhgg I had originally imagined using this library for a Flask implementation as a separate project, and hoping for this one to become the de-facto Python implementation of GraphQL... If anyone is interested in that, let me know :)

**Comment by jhgg** [comment]
I think @dittos vision is to have the bare GraphQL API that can be used to do whatever. Then ontop of it a more Pythonic API, Django / SQL Alchemy Support. 

I think whatever direction it takes, #28 needs to be addressed to support as broad a range of execution environments, as Python is not like Node at all as we don't have a single event loop and promise implementation in the language (aside from what was standardized in py3x). We've got Eventlets, Stackless, Gevent, Twisted, Tornado, Asyncio, etc... the list goes on. I could see this as being a "core" library with a stable API that a django, sql alchemy, etc... integration could be built off of. 

My use-case for this would be to run GraphQL alongside Django ontop of Gevent to parallelize queries to the database.

**Comment by jhgg** [comment]
I think the best solution here would be to allow parallel execution #28 and the parser #29 to be pluggable and then build out an ecosystem of GraphQL integrations ontop of the core library as separate packages.

**Comment by rawls238** [comment]
I agree with @woodb here, we should leave this implementation as a "core" GraphQL API that runs across all supported Python versions (i.e. >= 2.6) and have additional Django, SQL Alchemy, etc. integrations on top of it.

**Comment by rawls238** [comment]
@jhgg let's close this and open a separate repo for django integration? I'm interested in doing the integration with SQL alchemy so I'll open up a separate repo for that if we agree that's the path we should go down

**Comment by jhgg** [comment]
Closing this in favor of Django support landing in graphene https://github.com/syrusakbary/graphene/tree/django

@syrusakbary - awesome jobbb!
