### ISSUE TITLE
error structure sometimes dict, sometimes object

### ISSUE THREAD

**Issue by faassen** [dittos/graphqllib#55]
When I use `format_error` on the `result.errors`, I sometimes get error objects and `format_error` works. But in other cases the information it is a `dict` and `format_error` fails. I think it would be best to choose one or the other for errors, not both.

**Comment by jhgg** [comment]
#51 should address more consistent handling of errors.

**Comment by dittos** [comment]
Now only unformatted errors will be returned: 5a5453049eefc47e9de7a520a417be49b8524fad

**Comment by faassen** [comment]
Okay, could simplify the code a lot in wsgi_graphql, thanks!
