### ISSUE TITLE
Fragment Resolution resolving fields for incorrect type.

### ISSUE THREAD

**Issue by jhgg** [dittos/graphqllib#56]
```
query testQuery {
    node(id: "test123") {
        id
        __typeName
        ...on TypeA {
            name
        }
   }
}
```

Assuming node returns an interface implemented by TypeA or TypeB. If node with id "test123" returns an object of type TypeB, it will still return name. (assuming TypeA and TypeB both have a field named Name). 

I'll write tests for this and check it out further. Noticed while testing https://github.com/jhgg/relaypy/

**Comment by dittos** [comment]
Good catch. I fixed it.
