### ISSUE TITLE
Validation Rules

### ISSUE THREAD

**Issue by dittos** [dittos/graphqllib#6]
## Porting guide
* https://github.com/graphql/graphql-js/tree/master/src/validation/rules -> `graphql/core/validation/rules.py`
* https://github.com/graphql/graphql-js/tree/master/src/validation/__tests__ -> `tests/core_validation/test_(rule_name).py`
* https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/harness.js -> `tests/core_validation/utils.py`

## Status
* [x] ArgumentsOfCorrectType.js
* [x] DefaultValuesOfCorrectType.js
* [x] FieldsOnCorrectType.js
* [x] FragmentsOnCompositeTypes.js
* [x] KnownArgumentNames.js
* [x] KnownDirectives.js
* [x] KnownFragmentNames.js
* [x] KnownTypeNames.js
* [x] LoneAnonymousOperation.js
* [x] NoFragmentCycles.js
* [x] NoUndefinedVariables.js
* [x] NoUnusedFragments.js
* [x] NoUnusedVariables.js
* [x] OverlappingFieldsCanBeMerged.js
* [x] PossibleFragmentSpreads.js
* [x] ProvidedNonNullArguments.js
* [x] ScalarLeafs.js
* [x] UniqueArgumentNames.js
* [x] UniqueFragmentNames.js
* [x] UniqueOperationNames.js
* [x] VariablesAreInputTypes.js
* [x] VariablesInAllowedPosition.js

**Comment by rawls238** [comment]
For now I'll tackle porting UniqueArgumentNames.js, UniqueFragmentNames.js, VariablesInAllowedPosition.js

**Comment by dittos** [comment]
I'm working on `KnownArgumentNames`.

**Comment by woodb** [comment]
Sounds good! I have ported over `KnownDirectives` tests in a similar fashion in PR #13

**Comment by jhgg** [comment]
Going to work on `ProvidedNonNullArguments`. 

Also, Hi @woodb. Good seeing you again :smile:

**Comment by gabriel-laet** [comment]
Hey! Just forked and started working on `NoUndefinedVariables` rule

**Comment by jhgg** [comment]
Will tackle `DefaultValuesOfCorrectType` next, PR For `ProvidedNonNullArguments` open #22.

**Comment by jhgg** [comment]
PR for `DefaultValuesOfCorrectType` open #23 - `KnownFragmentNames` up next.

**Comment by jhgg** [comment]
PR for `KnownFragmentNames` open #24, `NoUnusedFragments` up next.

**Comment by jhgg** [comment]
PR for `NoUnusedFragments` open #25, `NoUnusedVariables` up next.

**Comment by jhgg** [comment]
PR for `NoUnusedVariables` is open #26 - `ArgumentsOfCorrectType` is up next, but I need #23 to be approved first. So I'll tackle `NoFragmentCycles` first.

**Comment by rawls238** [comment]
@jhgg let me know which ones you want to tackle and I'll implement the rest of them

**Comment by jhgg** [comment]
@rawls238  see above!

**Comment by rawls238** [comment]
I'll tackle these by the end of the weekend if that's cool with you guys @jhgg @dittos :

 PossibleFragmentSpreads.js
 OverlappingFieldsCanBeMerged.js
VariablesInAllowedPosition.js
NoUndefinedVariables.js

**Comment by jhgg** [comment]
I can take whatever if needed. I have another 3 hrs left today allocated to work on this. `NoUndefinedVariables` is an easy one I can KO.

**Comment by jhgg** [comment]
PR for `NoFragmentCycles` open #27  - Next up: `NoUndefinedVariables`.

**Comment by jhgg** [comment]
`OverlappingFieldsCanBeMerged` is going to be a hard one. I think it's gonna be the most complex rule.

**Comment by jhgg** [comment]
I'm going to hold off on doing more until @dittos merges all the pending in, so we can see where we're at. After merge I will work on `NoUndefinedVariables` and `ArgumentsOfCorrectType`.

**Comment by rawls238** [comment]
@jhgg I'm working on NoUndefinedVariables right now

**Comment by jhgg** [comment]
@rawls238 edited my above.

**Comment by rawls238** [comment]
nice @jhgg! looks like we should hopefully be done with this by the end of the weekend

**Comment by gabriel-laet** [comment]
Hey guys, I left a comment here yesterday, not sure if this is any useful, but I started working on `NoUndefinedVariables`: https://github.com/gabriel-laet/graphql-py/commit/a98a3dd9eab0e96ed49cc6c93a7623df37b302bb

Still needs work, I will probably finish it tomorrow.

**Comment by rawls238** [comment]
heh looks like everybody wants to implement that rule :P. Looks like you're rather far along @gabriel-laet so I'll let you finish that up

**Comment by gabriel-laet** [comment]
@rawls238 Alright, I will send the PR as soon as I finish it. Haha, yeah, I got an easy one to start contributing

**Comment by jhgg** [comment]
I made some comments @gabriel-laet

**Comment by gabriel-laet** [comment]
@jhgg https://github.com/dittos/graphql-py/pull/31

**Comment by jhgg** [comment]
Woop. Merged. Up next for me is `ArgumentsOfCorrectType`. 

In terms of complexity of what's left (from most to least difficult):

1. `OverlappingFieldsCanBeMerged`.
2. `VariablesInAllowedPosition`.
3. `PossibleFragmentSpreads`. 

Who is brave enough? :muscle:

**Comment by rawls238** [comment]
I almost have ```VariablesInAllowedPosition``` done and have started on ```PossibleFragmentSpreads```.

@jhgg @gabriel-laet one of you guys want to take on OverlappingFields?

**Comment by jhgg** [comment]
I will take on OverlappingFieldsCanBeMerged but it will probably take me a while. Some complex logic and idioms need to be translated.

**Comment by rawls238** [comment]
:+1: woo

**Comment by woodb** [comment]
Nice! This has been crazy awesome to watch get built out. Fantastic effort all around! :beers:

**Comment by jhgg** [comment]
`ArgumentsOfCorrectType` PR ready - #37

**Comment by gabriel-laet** [comment]
I can start to work on OverlappingFields or any other, where do you think I can help? @woodb @jhgg

**Comment by jhgg** [comment]
I'm working on `OverlappingFieldsCanBeMerged`.

**Comment by jhgg** [comment]
PR for `OverlappingFieldsCanBeMerged` is open! #47

**Comment by dittos** [comment]
Thanks @jhgg @gabriel-laet @rawls238 @woodb !
