### ISSUE TITLE
Implement Remaining Utilities

### ISSUE THREAD

**Issue by jhgg** [dittos/graphqllib#64]
In https://github.com/graphql/graphql-js/tree/master/src/utilities
## Porting Guide
- https://github.com/graphql/graphql-js/tree/master/src/utilities -> `graphql/core/utils/(util_name).py`
- https://github.com/graphql/graphql-js/tree/master/src/utilities/__tests__ -> `tests/core_utils/test_(util_name).py`
## Remaining utilities.
- [x] `TypeInfo`
- [ ] `astFromValue` #63 #62 
- [ ] `buildASTSchema`
- [ ] `buildClientSchema`
- [ ] `introspectionQuery`
- [ ] `isValidJSValue`
- [X] `isValidLiteralValue`
- [ ] `schemaPrinter`
- [X] `typeFromAST`
- [ ] `valueFromAST`
- [ ] `getOperationAST`

**Comment by faassen** [comment]
I looked at `isValidJSValue`, but there's an `is_valid_value` already in `graphql.core.execution.values` that looks like a port. There are no tests for this that I can find, but neither are there any direct tests in JavaScript.

I'll create a separate issue for discussing `is_nullish` (previously discussed here).

**Comment by faassen** [comment]
P.S. The first hyperlink to the `utilities` directory is broken in the issue text.

**Comment by jhgg** [comment]
The links are working fine for me o.O

**Comment by rawls238** [comment]
@jhgg I'll take a crack at schemaPrinter

**Comment by jhgg** [comment]
Moved https://github.com/graphql-python/graphql-core/issues/5
