### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by syrusakbary** [dittos/graphqllib#68]
I've built two packages in the top of `graphqllib`, but it gets a little bit painful to install the `graphqllib` dependency.
It will be much easier if the library is uploaded into pypi :)

Thanks!

**Comment by jhgg** [comment]
Still haven't hit v0.1 yet! Perhaps we can put up a beta?

**Comment by syrusakbary** [comment]
We can upload it to PyPI as pre release version. So it will not be default when people try to install it unless they specify the dev version.
http://pip.readthedocs.org/en/latest/reference/pip_install/#pre-release-versions

**Comment by jhgg** [comment]
We have an alpha package now available under [`graphql-core`](https://github.com/graphql-python/graphql-core).

https://pypi.python.org/pypi/graphql-core/0.1a0
